image: "python:3.7"

before_script:
  - pip install -r requirements_dev.txt

stages:
  - Static Analysis

black:
  stage: Static Analysis
  script:
    - black --check ./

flake8:
  stage: Static Analysis
  script:
  - flake8